name: Maven Build

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3  # Update to the latest version

      - name: Set up JDK 18
        uses: actions/setup-java@v3  # This already uses a recent version
        with:
          java-version: '18'
          distribution: 'temurin'

      - name: Run tests in NW-T1
        run: mvn -f ./NW-T1/pom.xml test


      

